--TODO: set Nerdtree - file explorer
--TODO: set theme, status line, colors, etc
--TODO: set for Lua development, format Lua files, autocomplete, lsp
--TODO: set for Go development, format .go files, autocomplete, lsp
--TODO: set for typscript development, format, tsx, jsx, js, ts files, autocomplete, lsp
--TODO: set for HTML, CSS development, format css, html files, autocomplete, lsp
--TODO: set telescope
--TODO: set treesitter
--TODO: set key mappings
--TODO: set productivity plugins
require("mrdupin")
